# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Helen Dockrell
email: dock0009@flinders.edu.au
description: > # this means to ignore newlines until "baseurl:"
 Hi! I'm a computational biologist working on my PhD thesis at Flinders University, South Australia. This site is something I'm developing in my bits and pieces of spare time, so bear with me. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: helen_reading

# Build settings
markdown: kramdown
